"""Report writers for CSV, JSON, and Markdown outputs.

Output format is intentionally explicit and stable so Bai can explain it and the
future dashboard can consume it without guessing column names.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Iterable


def write_csv(path: Path, rows: list[dict], fieldnames: list[str]) -> None:
    """Write rows to CSV with a stable header even when there are no rows."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, data: dict) -> None:
    """Write pretty JSON for dashboard/web app consumption."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def write_markdown_summary(path: Path, overview: dict, attackers: list[dict], incidents: list[dict], hidden: list[dict]) -> None:
    """Write a concise but complete Markdown summary for humans."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("# H1 Incident Analysis Summary")
    lines.append("")
    lines.append("> Generated by `Dorm/code/run_analysis.py`. This report is script-generated, not manual line-by-line reading.")
    lines.append("")
    lines.append("## 1. Overview")
    lines.append("")
    for key, value in overview.items():
        lines.append(f"- **{key}**: {value}")
    lines.append("")
    lines.append("## 2. WHO ARE THEY — Top Suspicious IPs")
    lines.append("")
    lines.append("| Rank | IP | Label | Score | Total Req | Peak RPM | 404 | 500 | Payload Hits | Reasons |")
    lines.append("|---:|---|---|---:|---:|---:|---:|---:|---:|---|")
    for idx, row in enumerate(attackers[:20], 1):
        lines.append(
            f"| {idx} | `{row['ip']}` | {row['label']} | {row['score']} | {row['total_requests']} | {row['peak_rpm']} | {row['status_404']} | {row['status_500']} | {row['payload_hits']} | {row['reasons']} |"
        )
    lines.append("")
    lines.append("## 3. WHEN — Incident Windows")
    lines.append("")
    if incidents:
        lines.append("| Window | Start | End | States | Peak Req/min | Peak 5xx/min | Reason |")
        lines.append("|---:|---|---|---|---:|---:|---|")
        for idx, row in enumerate(incidents, 1):
            lines.append(
                f"| {idx} | {row['start_time']} | {row['end_time']} | {row['states_seen']} | {row['peak_requests']} | {row['peak_5xx']} | {row['reason']} |"
            )
    else:
        lines.append("No non-normal incident windows detected by current thresholds.")
    lines.append("")
    lines.append("## 4. HIDDEN BONUS — Clue Candidates")
    lines.append("")
    if hidden:
        lines.append("| Candidate | Confidence | Type | Decode | Reason | Endpoint |")
        lines.append("|---|---|---|---|---|---|")
        for row in hidden[:20]:
            endpoint = str(row.get("endpoint", ""))[:120].replace("|", "\\|")
            lines.append(
                f"| `{row['candidate']}` | {row['confidence']} | {row['clue_type']} | {row['decode_method']} | {row['reason']} | `{endpoint}` |"
            )
    else:
        lines.append("No hidden-bonus candidates detected by current clue rules.")
    lines.append("")
    lines.append("## 5. Important Limitations")
    lines.append("")
    lines.append("- This log format does **not** include actual response time, so slow/unstable periods are inferred from traffic and error spikes.")
    lines.append("- This log format does **not** include User-Agent or request body, so tool fingerprinting and POST-body payloads are unavailable.")
    lines.append("- Scores are explainable heuristics for prioritization; final claims should cite evidence rows.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
